navs:
  prrel:
    - title: Physique
      href: physique/
    - title: Chimie
      href: chimie/
    - title: Mécanique
      href: mecanique/
    - title: Mathématiques
      href: maths/
    - title: Archi
      href: architecture/
    - title: Info
      href: informatique/
  l3/s1:
    - title: Réseau
      href: reseau/
    - title: Graphes
      href: graphes/
    - title: P. Fonctionnelle
      href: fonctionnelle/
    - title: P. Logique
      href: logique/
    - title: Complexité
      href: complexite/
  l3/s2:
    - title: BDD
      href: bdd/
    - title: P. Système
      href: systeme/
    - title: P. Linéaire
      href: lineaire/
    - title: POO
      href: poo/
    - title: G. Logiciel
      href: logiciel/
    - title: Simu
      href: simulation/
    - title: Anglais
      href: anglais/
  m1/s1:
    - title: Compilation
      href: compilation/
    - title: Architecture
      href: architecture/

# Build settings
markdown: redcarpet
exclude: [Gemfile, Gemfile.lock, .gitignore, Rakefile, README.md]
